### ISSUE TITLE
Twitter plugin doesn't resolve HTML entities

### ISSUE THREAD

**Issue by janc13** [ward/irc-butler#26]
The Twitter plugin doesn't resolve HTML entities like `&amp;`

For example:

    <Vaanir> https://twitter.com/watfordpolfooty/status/805126595329617921
    <irc-butler> [TWITTER] @WatfordPolFooty: It's with much sadness that the Watford fan that collapsed at West Brom today unfortunately died. My thoughts are with his Family &amp; friends.

**Comment by ward** [comment]
Fixed in https://github.com/ward/irc-butler/commit/d6d03e63ea99ed652b7d0ed5891e397db3c7e674
